{
  config,
  lib,
  osConfig ? { },
  ...
}:

let
  cfg = config.gm.shell;

  baseName = name: lib.last (lib.splitString "/" name);

  homebrewEntryName = entry: if lib.isString entry then entry else entry.name or "";

  homebrewNames = lib.concatMap (
    entry:
    let
      name = homebrewEntryName entry;
    in
    lib.filter (value: value != "") [
      name
      (baseName name)
    ]
  ) ((osConfig.homebrew.brews or [ ]) ++ (osConfig.homebrew.casks or [ ]));

  packageNames = map lib.getName config.home.packages;

  commandAliases = {
    fzf = [ "fzf-tmux" ];
    "kubernetes-cli" = [ "kubectl" ];
  };

  commandsForName = name: [ name ] ++ (commandAliases.${name} or [ ]);

  programCommands =
    lib.optional (config.programs.home-manager.enable or false) "home-manager"
    ++ lib.optional (config.programs.git.enable or false) "git";

  availableCommands = lib.unique (
    lib.concatMap commandsForName (packageNames ++ homebrewNames) ++ programCommands
  );

  hasCommand = command: builtins.elem command availableCommands;

  pluginCommands = {
    direnv = "direnv";
    fnm = "fnm";
    kubernetes = "kubectl";
    zoxide = "zoxide";
  };

  pluginEnabled =
    plugin:
    let
      command = pluginCommands.${plugin} or null;
    in
    command == null || hasCommand command;

  activePlugins = lib.filter pluginEnabled cfg.plugins;

  commandShellAliases = lib.foldl' (
    aliases: command: aliases // lib.optionalAttrs (hasCommand command) cfg.aliasGroups.${command}
  ) { } (builtins.attrNames cfg.aliasGroups);

  shellAliases = commandShellAliases // cfg.extraAliases;

  generatedInit = ''
    # Generated by Home Manager from modules/home/shell.nix.
    export SHELL_CONFIG="$HOME/.config/shell"
    GM_SHELL_NAME="${cfg.program}"

    shell_plugins=(
    ${lib.concatMapStringsSep "\n" (plugin: "  ${plugin}") activePlugins}
    )

    . "$SHELL_CONFIG/init.sh"
  '';
in
{
  options.gm.shell = {
    enable = lib.mkEnableOption "managed shell configuration";

    program = lib.mkOption {
      type = lib.types.enum [
        "bash"
        "zsh"
      ];
      default = "zsh";
      description = "Shell that loads the shared configuration.";
    };

    configDir = lib.mkOption {
      type = lib.types.path;
      default = ../../config/shell;
      description = "Directory containing shared shell configuration and plugin snippets.";
    };

    plugins = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [
        "cargo"
        "fnm"
        "kubernetes"
        "node"
        "zoxide"
        "direnv"
      ];
      description = "Shell plugins to load, in order.";
    };

    aliasGroups = lib.mkOption {
      type = lib.types.attrsOf (lib.types.attrsOf lib.types.str);
      default = { };
      example = {
        git = {
          g = "git";
          gs = "git status";
        };
      };
      description = "Shell aliases grouped by command. Each group is enabled only when the command is available.";
    };

    extraAliases = lib.mkOption {
      type = lib.types.attrsOf lib.types.str;
      default = { };
      example = {
        ll = "ls -lah";
        ".." = "cd ..";
      };
      description = "Shell aliases that are always created.";
    };
  };

  config = lib.mkIf cfg.enable (
    lib.mkMerge [
      {
        home.file.".config/shell".source = cfg.configDir;
      }

      (lib.mkIf (cfg.program == "bash") {
        programs.bash = {
          enable = true;
          inherit shellAliases;
          initExtra = lib.mkAfter generatedInit;
          profileExtra = ''
            if [ -f "$HOME/.profile_custom" ]; then
              . "$HOME/.profile_custom"
            fi
          '';
        };
      })

      (lib.mkIf (cfg.program == "zsh") {
        programs.zsh = {
          enable = true;
          inherit shellAliases;
          envExtra = ''
            # Keep inherited values compact before startup code scans fpath.
            typeset -U path PATH fpath FPATH
          '';
          initContent = lib.mkAfter generatedInit;
        };
      })
    ]
  );
}
