{
  config,
  lib,
  osConfig ? { },
  ...
}:

let
  cfg = config.gm.zsh;

  baseName = name: lib.last (lib.splitString "/" name);

  homebrewEntryName = entry: if lib.isString entry then entry else entry.name or "";

  homebrewNames = lib.concatMap (
    entry:
    let
      name = homebrewEntryName entry;
    in
    lib.filter (value: value != "") [
      name
      (baseName name)
    ]
  ) ((osConfig.homebrew.brews or [ ]) ++ (osConfig.homebrew.casks or [ ]));

  packageNames = map lib.getName config.home.packages;

  commandAliases = {
    fzf = [ "fzf-tmux" ];
    "kubernetes-cli" = [ "kubectl" ];
  };

  commandsForName = name: [ name ] ++ (commandAliases.${name} or [ ]);

  programCommands =
    lib.optional (config.programs.home-manager.enable or false) "home-manager"
    ++ lib.optional (config.programs.git.enable or false) "git";

  availableCommands = lib.unique (
    lib.concatMap commandsForName (packageNames ++ homebrewNames) ++ programCommands
  );

  hasCommand = command: builtins.elem command availableCommands;

  pluginCommands = {
    direnv = "direnv";
    fnm = "fnm";
    kubernetes = "kubectl";
    tmux = "tmux";
    zoxide = "zoxide";
  };

  pluginEnabled =
    plugin:
    let
      command = pluginCommands.${plugin} or null;
    in
    command == null || hasCommand command;

  activePlugins = lib.filter pluginEnabled cfg.plugins;

  aliasGroups = {
    bat = {
      c = "bat";
    };

    codex = {
      dcodex = "codex --dangerously-bypass-approvals-and-sandbox";
    };

    git = {
      g = "git";
      ga = "git add";
      gb = "git branch";
      gd = "git diff";
      gs = "git status";
      grs = "git restore --staged";
      gcm = "git commit -m";
      gds = "git diff --staged";
      gpl = "git pull";
      gpo = "git push -u origin HEAD";
      gpu = "git push";
    };

    home-manager = {
      hm = "home-manager";
    };

    kubectl = {
      k = "kubectl";
    };

    terraform = {
      tf = "terraform";
    };
  };

  commandShellAliases = lib.foldl' (
    aliases: command: aliases // lib.optionalAttrs (hasCommand command) aliasGroups.${command}
  ) { } (builtins.attrNames aliasGroups);

  shellAliases = commandShellAliases // cfg.extraAliases;

  generatedInit = ''
    # Generated by Home Manager from modules/home/zsh.nix.
    export ZSH="$HOME/.config/zsh/config"

    plugins=(
    ${lib.concatMapStringsSep "\n" (plugin: "  ${plugin}") activePlugins}
    )

    source "$ZSH/init.sh"
  '';
in
{
  options.gm.zsh = {
    enable = lib.mkEnableOption "managed zsh configuration";

    configDir = lib.mkOption {
      type = lib.types.path;
      default = ../../config/zsh/config;
      description = "Directory containing zsh init files and plugin snippets.";
    };

    plugins = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [
        "cargo"
        "fnm"
        "kubernetes"
        "node"
        "tmux"
        "zoxide"
        "direnv"
      ];
      description = "Zsh plugins to load, in order.";
    };

    extraAliases = lib.mkOption {
      type = lib.types.attrsOf lib.types.str;
      default = { };
      example = {
        ll = "ls -lah";
        ".." = "cd ..";
      };
      description = "Zsh aliases that are always created, regardless of installed commands.";
    };
  };

  config = lib.mkIf cfg.enable {
    home.file.".config/zsh/config".source = cfg.configDir;

    programs.zsh = {
      enable = true;
      inherit shellAliases;
      initContent = lib.mkAfter generatedInit;
    };
  };
}
