{
  config,
  lib,
  osConfig ? { },
  ...
}:

let
  cfg = config.gm.zsh;

  baseName = name: lib.last (lib.splitString "/" name);

  homebrewEntryName = entry: if lib.isString entry then entry else entry.name or "";

  homebrewNames = lib.concatMap (
    entry:
    let
      name = homebrewEntryName entry;
    in
    lib.filter (value: value != "") [
      name
      (baseName name)
    ]
  ) ((osConfig.homebrew.brews or [ ]) ++ (osConfig.homebrew.casks or [ ]));

  packageNames = map lib.getName config.home.packages;

  commandAliases = {
    fzf = [ "fzf-tmux" ];
    "kubernetes-cli" = [ "kubectl" ];
  };

  commandsForName = name: [ name ] ++ (commandAliases.${name} or [ ]);

  programCommands =
    lib.optional (config.programs.home-manager.enable or false) "home-manager"
    ++ lib.optional (config.programs.git.enable or false) "git";

  availableCommands = lib.unique (
    lib.concatMap commandsForName (packageNames ++ homebrewNames) ++ programCommands
  );

  hasCommand = command: builtins.elem command availableCommands;

  pluginCommands = {
    direnv = "direnv";
    fnm = "fnm";
    kubernetes = "kubectl";
    tmux = "tmux";
    zoxide = "zoxide";
  };

  pluginEnabled =
    plugin:
    let
      command = pluginCommands.${plugin} or null;
    in
    command == null || hasCommand command;

  activePlugins = lib.filter pluginEnabled cfg.plugins;

  commandShellAliases = lib.foldl' (
    aliases: command: aliases // lib.optionalAttrs (hasCommand command) cfg.aliasGroups.${command}
  ) { } (builtins.attrNames cfg.aliasGroups);

  shellAliases = commandShellAliases // cfg.extraAliases;

  generatedInit = ''
    # Generated by Home Manager from modules/home/zsh.nix.
    export ZSH="$HOME/.config/zsh"

    plugins=(
    ${lib.concatMapStringsSep "\n" (plugin: "  ${plugin}") activePlugins}
    )

    source "$ZSH/init.sh"
  '';
in
{
  options.gm.zsh = {
    enable = lib.mkEnableOption "managed zsh configuration";

    configDir = lib.mkOption {
      type = lib.types.path;
      default = ../../config/zsh;
      description = "Directory containing zsh init files and plugin snippets.";
    };

    plugins = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [
        "cargo"
        "fnm"
        "kubernetes"
        "node"
        "tmux"
        "zoxide"
        "direnv"
      ];
      description = "Zsh plugins to load, in order.";
    };

    aliasGroups = lib.mkOption {
      type = lib.types.attrsOf (lib.types.attrsOf lib.types.str);
      default = { };
      example = {
        git = {
          g = "git";
          gs = "git status";
        };
      };
      description = "Zsh aliases grouped by command. Each group is enabled only when the command is available.";
    };

    extraAliases = lib.mkOption {
      type = lib.types.attrsOf lib.types.str;
      default = { };
      example = {
        ll = "ls -lah";
        ".." = "cd ..";
      };
      description = "Zsh aliases that are always created, regardless of installed commands.";
    };
  };

  config = lib.mkIf cfg.enable {
    home.file.".config/zsh".source = cfg.configDir;

    programs.zsh = {
      enable = true;
      inherit shellAliases;
      envExtra = ''
        # Keep inherited values from nested shells compact before startup
        # code scans fpath for completions.
        typeset -U path PATH fpath FPATH
      '';
      initContent = lib.mkAfter generatedInit;
    };
  };
}
